import Head from "next/head";
import Banner from "../components/Banner";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import SectionCards from "../components/SectionCards";
import { getPopularVideos, getVideos } from "../lib/videos";

export async function getServerSideProps() {
  const disneyVideos = (await getVideos("disney trailer")) || null;
  const productivityVideos = (await getVideos("Productivity")) || null;
  const travelVideos = (await getVideos("indie music")) || null;
  const popularVideos = (await getPopularVideos()) || null;

  return {
    props: { disneyVideos, travelVideos, productivityVideos, popularVideos }, // will be passed to the page component as props
  };
}

export default function Home({ disneyVideos, travelVideos, productivityVideos, popularVideos }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
        <Navbar />
        <Banner videoId="4zH5iYM4wJo" title="Clifford the red dog" subTitle="a very cute dog" imgUrl="/static/clifford.webp" />

        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large" />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards title="Productivity" videos={productivityVideos} size="medium" />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}
